### PR TITLE
Realm of authorization may differ from the scope of use

### PR DESCRIPTION
**Pull request by crowar**

### CODE REVIEW

**Review by sps-campbellwray — APPROVED** [review]
Thanks @crowar this will be a helpful change, approved and merged

**Comment by pzimmermaninmo** [comment]
@sps-campbellwray Is this change currently available in the latest nuget package?  I was looking for it in my config options but didn't see it there.

**Comment by campbellwray** [comment]
@pzimmermaninmo I have taken a look, and no it unfortunately is not available in the NuGet version yet. 

I will create a release next week and let you know when it is done.

**Comment by pzimmermaninmo** [comment]
> @pzimmermaninmo I have taken a look, and no it unfortunately is not available in the NuGet version yet.
> 
> I will create a release next week and let you know when it is done.

Appreciate it.  Hopefully the sooner the better because I am in the process of building out a feature that requires it and I'd prefer to not have to manually build a DLL to use instead.

**Pull request merged**
